project:
  type: book

lang: es

book:
  title: "Cibernética para la sustentabilidad"
  author: "Luis Guillermo García Jácome"
  date: "5/9/2026"
  chapters:
    - index.qmd
    - programa.qmd
    - part: "I. Fundamentos del análisis de datos"
      chapters:
        - modulo_01/01_cibernetica_y_analisis_de_datos/cibernetica_y_analisis_de_datos.qmd
        - modulo_01/02_introduccion_a_las_hojas_de_calculo/introduccion_a_las_hojas_de_calculo.qmd
        - modulo_01/03_procesamiento_y_manejo_de_datos/procesamiento_y_manejo_de_datos.qmd
        - modulo_01/practica_01/practica_01.qmd
    - part: "II. Visualización y comunicación de datos"
    - part: "III. Introducción a la programación en R"
    - part: "IV. Métodos computacionales para la sustentabilidad"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



