# Procesamiento y manejo de datos

## Material de la sesión 

### Presentación

```{=html}
<iframe src="https://slides.com/bmbi/procesamiento-y-manejo-de-datos/embed" width="576" height="420" title="Procesamiento y manejo de datos" scrolling="no" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
```
### Hoja de cálculo

- [Hoja de cálculo utilizada en esta sesión](https://docs.google.com/spreadsheets/d/1s6u58dalvDiU4eJYTZInifFJBlIkQZVf7P8PPbow1kk/edit?usp=sharing)

### Scripts 

- [Script para preparar datos del tutorial](./preparar_datos_tutorial.R)
- [Script para preparar datos del ejercicio](./preparar_datos_ejercicio.R)


## Principales archivos de datos

- Existen muchos formas para almacenar datos. Cuando trabajamos con una cantidad no tan grande de datos podemos almacenar la información en archivos de datos como archivos de excel `.xls`, archivos de extensión `.txt` o `.csv`. Sin embargo, cuando se tienen enormes cantidades de datos, es mejor almacenar estos datos en bases de datos, que son programas especializados para organizar y almacenar datos de una manera eficiente. 
- Una de las formas más faciles y amigables de almacenar datos es con archivos de excel, no obstante, esta forma de compartir datos tiene varias limitaciones. Por ejemplo, una persona que no tenga excel en su computadora no podrá abrir los archivos. Además como excel es un programa que le pertenece a Excel y no cualquiera puede saber cómo funciona internamente el programa si un día Microsoft decide dejar de desarrollar Excel la información almacenada en estos archivos se quedaría atrapada y obsoleta. Por lo tanto, no podemos depender de estos archivos para almacenar información.
- Un formato de archivo que es muy accesible para almacenar datos son los archivos con extensión `.csv`. Estos son archivos que se pueden abrir con cualquier editor de texto como el "Block de Notas" y por lo tanto no dependen de ninguna empresa para que funcionen. `csv` significa Comma Separated Values, es decir, valores separados por comas. Si abrimos este archivo con un editor de notas, veremos que tenemos tal cual eso: filas de valores numéricos o cadenas, separadas por comas. Generalmente la primer fila son los nombres de las columnas y en las siguientes filas vienen los valores correspondientes en el orden correspondiente.
- Sí abrimos un archivo `.csv` con un programaa de hojas de cálculo como Excel o Google sheets, estos automáticamente lo formatearán como una tabla.
- Además de los archivos `.csv` hay otros formatos similares como los `.tsv` (_Tab_ separated values), que son iguales que los archivos csv pero en lugar de usar comas para separar los valore se usan tabulaciones. Asi mimso hay otros formatos comunes como los `.json` que tienen estructuras más complicadas, pero también son archivos que se pueden abrir con cualquier programa y cuya información se puede leer como una tabla.

## Importar datos

- Para importar un archivo `csv` en Google sheets debemos dar click en: Archivo > Importar > Subir. Luego debemos tener cuidado en cómo queremos importar los datos ya que nos da varias opciones como: Importarlos en una nueva hoja de cálculo (un nuevo archivo), Reemplazar la hoja de cálculo actual (borrando todo lo que ya tenemos), Agregarla como una hoja nueva dentro de la misma hoja y Agregarla a la hoja donde estamos (reemplazando o no lo que tenemos dentro de ella).

## Fijar filas

- Cuando tenemos tablas de datos con muchas filas es útil fijar la primera fila con los nombres para saber qué contiene cada columna.
- Para fijar la primera fila podemos arrastrar la barra gris arriba de la fila 1 o dar click en Ver > Inmovilizar > 1 fila.

## Limpiar datos

- Uno de los pasos más importantes de ciencia de datos es la preparación de los datos para poder analizarlos y generar algo útil con ellos.
- Las bases de datos muy rara vez vienen completamente limpias y listas para su análisis, más bien vienen llenos de inconsistencias. 
- Algunos de los principales problemas con los datos suelen ser:
   - Nombres de columna raros (en código, nombres muy largos, nombres en otros idiomas)
   - Caracteres raros (caractéres no latinos, problemas de codificación)
   - Formato de texto inconsistente (texto en mínusculas, en mayúsculas, capitalizado)
   - Datos vacios y nulos (una forma común para representar datos nulos es `NA`)
   - Valores inconsistentes (mezcla de números y texto en una misma columna, diversas formas de representar un mismo valor)
   - Información repartida en varios archivos (información contenida en catálogos o archivos de metadatos)
   - Registros duplicados
   - Errores ortográficos
   - etc.
- La limpieza de datos puede ser un proceso largo y requiere algo de investigación como si se fuera un detective. Muchas veces la limpieza de datos es el proceso que más tiempo toma al realizar un análisis de datos.
- En inglés al preprocesamiento de datos (que además de incluir la limpieza puede incluir otras modificaciones a los datos) se conoce como [data wrangling](https://www.ibm.com/es-es/think/topics/data-wrangling).
- Algunas herramientas útiles en Google sheets para la limpieza de datos son:
   - **Buscar y reemplazar**
      - _Editar_ > _Buscar y reemplazar_ (`CTRL`+`H`)
      - Permite buscar una cadena de texto en todo el documento, una hoja o un rango específico y reemplazarla por otra cadena de texto deseada (muchas veces la cadena de reemplazo deseada es un espacio en blanco)
   - **Sugerencias de borrado**
      - _Datos_ > _Limpieza de datos_ > _Sugerencia de borrado_
      - Esta opción analiza los datos y abre una ventana emergente que sugiere cambios que podemos hacerle a los datos. En particular es útil para **identificar y eliminar duplicados**. En estas opciones uno puede reesaltar los datos duplicados y aceptar o rechazar eliminarlos uno por uno o todos de un jalón.
   - **Estadística de columna**
      - _Datos_ > _Estadística de columna_
      - Esta opción genera un análisis estadístico rápido de los datos de una columna y provee una ventana emergente que da gráficos útiles para entender los valores en la columna (e.g., histogramas, listas de valores únicos, gráficos de barras de conteos de valores). Esta opción es útil para identificar valores raros en una columna que debamos tratar. 

## Ordenar

- Para ordenar datos de acuerdo a los valores de una columna podemos dar click en el triangulito en la letra de la columna y luego seleccionar si queremos ordenar los datos de manera ascendente (Ordenrar hoja de la A a la Z) o descendente (Ordenar hoja de la Z a la A).
- Si quisiéramos ordenar por los valores de dos columnas, debemos aplicar un ordenamiento seguido del otro.

## Filtrar

- Filtrar permite quedarse sólo con los valores que cumplen cierto criterio para una o varias columnas. 
- Para filtrar primero debemos entrar al modo de filtro para una tabla. Para ello primero debemos seleccionar toda la tabla de datos. Para seleccionar una tabla podemos poner el cursor sobre cualquier celda que contenga datos de la tabla y presionar `CTRL`+`A` (nota que si presionas `CTRL`+`A` dos veces se seleccionarán todas las celdas de la hoja)
- Ya que tenemos la tabla seleccionada damos click en el ícono de aplicar filtro en la barra de herramientas y notarás que los bordes de la tabla se ponen verdes indicando que estamos en el modo de filtro.
- Para filtrar podemos dar click en las tres rayas en forma de tríangulo que salen al lado del nombre de las columnas, ahí podemos elegir varias opciones:
   - Filtrar por un valor, útil para filtrar por valores específicos de una columna de texto
   - Filtrar por condición, útil para aplicar criterios más complejos como revisar si un valor numérico es mayor o menor que un valor determinado, o para reconocer un patrón de texto en una columna.
- Nota que se pueden aplicar múltiples filtros de varias columnas simultáneamente.
- Para salir del modo filtro solo debemos dar click de nuevo en el ícono de filtro y se mostrarán de nuevo todos los valores. 

## Crear gráficos

- Google sheets tiene funcionalidades básicas para crear gráficos. Para ello primero debemos seleccionar los datos que queremos graficar y luego dar click en Insertar > Gráfico. 
- A partir de los datos seleccionados Google sheets sugiere automáticamente un gráfico, que muchas veces es el adecuado, sin embargo, muchas veces es poco útil y uno debe configurar manualmente el tipo de gráfico y elegir correctamente los valores a mapear. 
- En este momento no profundizaremos mucho en configurar gráficos ya que utilizaremos otras herramientas más poderosas para crear una mayor diversidad de gráficos.

## Función `UNIQUE`

- La función `UNIQUE` permite quedarse únicamente con los valores distintos de un rango de valores. Esta función recibe como único argumento el rango de valores y retorna un arreglo con los valores únicos.


## Funciones de búsqueda

- Muchas veces nos enfrentamos al problema de querer agregar una nueva columna en una tabla basada en un identificador que tenemos en otra columna. 
- Por ejemplo podríamos tenemos una tabla con datos de la población de los países para distintos años pero la tabla podría no incluir el nombre de cada país sino un identificador numérico. Por otro lado podríamos tener una tabla que tiene los identificadores y el nombre del país. ¿Cómo las juntasmos?
- Para solucionar este problema existen las funciones de búsqueda `VLOOKUP`, `HLOOKUP` y `XLOOKUP`.

### `VLOOKUP`

- `VLOOKUP` hace búsquedas verticales y recibe como argumentos:
   1. El valor que queremos buscar,
   2. El rango de datos donde está el valor que buscamos y el valor que queremos agregar
   3. El índice de la columna donde está el valor que queremos agregar considerando que la primera columna del rango es 1.
   4. Un argumento booleano que determina si se quiere una búsqueda exacta (FALSE) o si se busca el valor menor más cercano (TRUE), que es útil sobre todo cuando el rango de datos a buscar está ordenado por un valor numérico.

### `HLOOKUP`

- `HLOOKUP` es equivalente a `VLOOKUP` pero en lugar de hacer búsquedas verticales hace búsquedas horizontales. Sus argumentos son los mismos a excepción del tercro que en este caso es el índice de la fila donde esþa el valor que queremos agregar (igual considerando que la primera fila del rango es la 1).

### `MATCH`

- Otra función util es la función `MATCH` la cual retorna el número de índice en el que está una búsqueda dentro de un rango. Esta tiene los siguientes argumentos:
  1. Valor a buscar,
  2. Intervalo donde buscar,
  3. El tipo de búsqueda, donde 0 es una búsqueda exacta, -1 el valor inferior más cercano y 1 el valor superior más cercano.
- Esta función es útil para usarla junto con `HLOOKUP` cuando se quiere cambiar de manera dinámica la fila con el valor a retronar.

### `INDEX`

- Una función que muchas veces va de la mano de la función `MATCH` es la función `INDEX`, la cual retorna el contenido de un arreglo especificado por la fila y columna de lo que queremos obtener. Esta función recibe:
   1. El rango de datos (un arreglo)
   2. El número de fila de los datos que se buscan
   3. El número de columna de los datos que se buscan.

### `XLOOKUP`

- `VLOOKUP` es muy poderosa pero tiene un par de limitaciones:
  1. Solo permite usar índices positivos en su segundo argumento, lo cual implica que la columna con el valor para reemplazar debe siempre estar a la derecha de la columna con los valores de búsqueda.
  2. Cuando no encuntra una entrada nos pone un error que se ve feo (esto no es tanto un problema)
- Una solución para esto es `XLOOKUP` la cual es mas flexible y poderosa y tiene los siguientes argumentos:
  1. El valor a buscar,
  2. El rango de búsqueda
  3. El rango de los valores a reemplazar, 
  4. El valor a poner cuando no se halla un valor en la búsqueda
  5. El modo de búsqueda: 0 búsqueda exacta, -1 buscar el valor menor más cercano, 1 buscar el valor mayor más cercano, y otras opciones más específicas.
